# Generated by Django 6.1.2 on 2026-10-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_stage_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('payment_method', models.CharField(choices=[('invoice', 'Invoice'), ('card', 'Card'), ('ach', 'Bank transfer (ACH)'), ('other', 'Other')], default='invoice', max_length=10)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='contract end / renewal date')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='renews automatically')),
                ('notice_days', models.PositiveSmallIntegerField(default=30, help_text='How many days before the renewal date either side must give notice.', verbose_name='notice period (days)')),
                ('billing_contact_name', models.CharField(blank=True, max_length=150)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('billing_contact_phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='clients.client')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'Contract & billing',
                'db_table': 'contract',
            },
        ),
    ]
