# Generated by Django 6.1.2 on 2026-10-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('five9', 'Five9'), ('convoso', 'Convoso'), ('ringcentral', 'RingCentral'), ('twilio', 'Twilio'), ('trustedform', 'TrustedForm'), ('jornaya', 'Jornaya'), ('lead_feed', 'Lead feed copy (CiV as extra destination)'), ('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('other_dialer', 'Other dialer'), ('other_sms', 'Other texting tool'), ('other_crm', 'Other CRM')], max_length=30)),
                ('kind', models.CharField(choices=[('dialer', 'Dialer'), ('sms', 'Texting tool'), ('certificates', 'Certificate account'), ('lead_feed', 'Lead feed copy'), ('crm', 'CRM')], editable=False, max_length=20)),
                ('label', models.CharField(blank=True, help_text='Optional, e.g. "Main dialer" when a client has two.', max_length=100)),
                ('credentials', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('not_connected', 'Not connected'), ('waiting_client', 'Waiting for client'), ('untested', 'Saved, not tested'), ('connected', 'Connected'), ('failed', 'Failed'), ('stale', 'Stale')], default='not_connected', editable=False, max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_message', models.CharField(blank=True, editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='clients.client')),
            ],
            options={
                'db_table': 'connection',
                'ordering': ['client__name', 'kind', 'provider'],
            },
        ),
    ]
