# Generated by Django 6.1.2 on 2026-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last checked'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.CharField(choices=[('Dialer', [('five9', 'Five9'), ('convoso', 'Convoso'), ('ringcentral', 'RingCentral'), ('other_dialer', 'Other dialer')]), ('Texting tool', [('twilio', 'Twilio'), ('other_sms', 'Other texting tool')]), ('Certificate account', [('trustedform', 'TrustedForm'), ('jornaya', 'Jornaya')]), ('Lead feed copy', [('lead_feed', 'Lead feed copy (CiV as extra destination)')]), ('CRM', [('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('other_crm', 'Other CRM')])], max_length=30, verbose_name='tool'),
        ),
    ]
