# Generated by Django 6.1.2 on 2026-10-10 19:56

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_stage_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('agreement', 'Service agreement'), ('annex_c', 'Annex C (test opt-out permission)'), ('statement', 'Signed statement (Insured states)'), ('dpa', 'Data processing agreement (DPA)'), ('other', 'Other')], default='agreement', max_length=20, verbose_name='type')),
                ('title', models.CharField(blank=True, help_text='Optional, e.g. "MSA v2, signed by J. Smith".', max_length=200)),
                ('file', models.FileField(blank=True, help_text='PDF, image or Word file, up to 20 MB. Kept privately on the server.', upload_to=apps.documents.models.upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'docx'])])),
                ('link', models.URLField(blank=True, help_text='If the file lives elsewhere (Google Drive, DocuSign…).', verbose_name='or link')),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='fingerprint (SHA-256)')),
                ('size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
