# Generated by Django 6.1.2 on 2026-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='growth', max_length=20)),
                ('start_date', models.DateField()),
                ('counsel_directed', models.BooleanField(default=True, verbose_name='lawyer-only mode')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
    ]
