# Generated by Django 6.1.2 on 2026-10-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'client company', 'verbose_name_plural': 'client companies'},
        ),
    ]
