# Generated by Django 6.1.2 on 2026-10-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_level',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
