# Generated by Django 6.1.2 on 2026-10-10 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def existing_clients(apps, schema_editor):
    """Clients made before stages existed: active ones become Active, turned-off ones Ended."""
    Client = apps.get_model('clients', 'Client')
    Client.objects.filter(is_active=True).update(status='active')
    Client.objects.filter(is_active=False).update(status='ended')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='onboarding', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('trial', 'Trial'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], max_length=20)),
                ('new_status', models.CharField(choices=[('trial', 'Trial'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='clients.client')),
            ],
            options={
                'db_table': 'client_status_change',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RunPython(existing_clients, migrations.RunPython.noop),
    ]
