# Generated by Django 6.1.2 on 2026-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='onboarding', max_length=20, verbose_name='stage'),
        ),
    ]
