# Generated by Django 6.1.2 on 2026-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_kind', models.CharField(choices=[('client_user', 'Client user'), ('staff', 'CiV staff'), ('system', 'System'), ('anonymous', 'Not signed in')], max_length=20)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, max_length=254)),
                ('client_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('object', models.CharField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'access log entry',
                'verbose_name_plural': 'access log',
                'db_table': 'access_log',
                'ordering': ['-at'],
            },
        ),
    ]
